

export const ADMIN_DELETEPRODUCT_REQUEST = 'USER_DELETEPRODUCT_REQUEST'
export const ADMIN_DELETEPRODUCT_SUCCESS = 'USER_DELETEPRODUCT_SUCCESS'
export const ADMIN_DELETEPRODUCT_FAIL = 'USER_DELETEPRODUCT_FAIL'


export const ADMIN_UPDATEPRODUCT_REQUEST = 'USER_UPDATEPRODUCT_REQUEST'
export const ADMIN_UPDATEPRODUCT_SUCCESS = 'USER_UPDATEPRODUCT_SUCCESS'
export const ADMIN_UPDATEPRODUCT_FAIL = 'USER_UPDATEPRODUCT_FAIL'

export const ADMIN_ADDCATEGORY_REQUEST = 'ADMIN_ADDCATEGORY_REQUEST'
export const ADMIN_ADDCATEGORY_SUCCESS = 'ADMIN_ADDCATEGORY_SUCCESS'
export const ADMIN_ADDCATEGORY_FAIL = 'ADMIN_ADDCATEGORY_FAIL'


export const ADMIN_DELETECATEGORY_REQUEST = 'ADMIN_ADDCATEGORY_REQUEST'
export const ADMIN_DELETECATEGORY_SUCCESS = 'ADMIN_ADDCATEGORY_SUCCESS'
export const ADMIN_DELETECATEGORY_FAIL = 'ADMIN_ADDCATEGORY_FAIL'

export const ADMIN_UPDATECATEGORY_REQUEST = 'ADMIN_UPDATECATEGORY_REQUEST'
export const ADMIN_UPDATECATEGORY_SUCCESS = 'ADMIN_UPDATECATEGORY_SUCCESS'
export const ADMIN_UPDATECATEGORY_FAIL = 'ADMIN_UPDATECATEGORY_FAIL'

export const USER_GETALLSUBCATEGORIES_REQUEST = 'USER_GETALLSUBCATEGORIES_REQUEST'
export const USER_GETALLSUBCATEGORIES_SUCCESS = 'USER_GETALLSUBCATEGORIES_SUCCESS'
export const USER_GETALLSUBCATEGORIES_FAIL = 'USER_GETALLSUBCATEGORIES_FAIL'

export const ADMIN_DELETESUBCATEGORY_REQUEST = 'ADMIN_ADDSUBCATEGORY_REQUEST'
export const ADMIN_DELETESUBCATEGORY_SUCCESS = 'ADMIN_ADDSUBCATEGORY_SUCCESS'
export const ADMIN_DELETESUBCATEGORY_FAIL = 'ADMIN_ADDSUBCATEGORY_FAIL'

export const ADMIN_UPDATESUBCATEGORY_REQUEST = 'ADMIN_UPDATESUBCATEGORY_REQUEST'
export const ADMIN_UPDATESUBCATEGORY_SUCCESS = 'ADMIN_UPDATESUBCATEGORY_SUCCESS'
export const ADMIN_UPDATESUBCATEGORY_FAIL = 'ADMIN_UPDATESUBCATEGORY_FAIL'

export const ADMIN_GETSUBCATEGORY_REQUEST = 'ADMIN_GETSUBCATEGORY_REQUEST'
export const ADMIN_GETSUBCATEGORY_SUCCESS = 'ADMIN_GETSUBCATEGORY_SUCCESS'
export const ADMIN_GETSUBCATEGORY_FAIL = 'ADMIN_GETSUBCATEGORY_FAIL'


export const ADMIN_GETCUSTOMERS_REQUEST = 'ADMIN_GETCUSTOMERS_REQUEST'
export const ADMIN_GETCUSTOMERS_SUCCESS = 'ADMIN_GETCUSTOMERS_SUCCESS'
export const ADMIN_GETCUSTOMERS_FAIL = 'ADMIN_GETCUSTOMERS_FAIL'

export const ADMIN_DELETECUSTOMER_REQUEST = 'ADMIN_DELETECUSTOMER_REQUEST'
export const ADMIN_DELETECUSTOMER_SUCCESS = 'ADMIN_DELETECUSTOMER_SUCCESS'
export const ADMIN_DELETECUSTOMER_FAIL = 'ADMIN_DELETECUSTOMER_FAIL'

export const OWNER_GETADMINS_REQUEST = 'OWNER_GETADMINS_REQUEST'
export const OWNER_GETADMINS_SUCCESS = 'OWNER_GETADMINS_SUCCESS'
export const OWNER_GETADMINS_FAIL = 'OWNER_GETADMINS_FAIL'

export const OWNER_DELETEADMIN_REQUEST = 'OWNER_DELETEADMIN_REQUEST'
export const OWNER_DELETEADMIN_SUCCESS = 'OWNER_DELETEADMIN_SUCCESS'
export const OWNER_DELETEADMIN_FAIL = 'OWNER_DELETEADMIN_FAIL'

export const OWNER_DELETADMIN_REQUEST = 'OWNER_DELETADMIN_REQUEST'
export const OWNER_DELETADMIN_SUCCESS = 'OWNER_DELETADMIN_SUCCESS'
export const OWNER_DELETADMIN_FAIL = 'OWNER_DELETADMIN_FAIL'


export const ADMIN_GETORDERS_REQUEST = 'ADMIN_GETORDERS_REQUEST'
export const ADMIN_GETORDERS_SUCCESS = 'ADMIN_GETORDERS_SUCCESS'
export const ADMIN_GETORDERS_FAIL = 'ADMIN_GETORDERS_FAIL'


export const ADMIN_APPROVEORDER_REQUEST = 'ADMIN_APPROVEORDER_REQUEST'
export const ADMIN_APPROVEORDER_SUCCESS = 'ADMIN_APPROVEORDER_SUCCESS'
export const ADMIN_APPROVEORDER_FAIL = 'ADMIN_APPROVEORDER_FAIL'


export const ADMIN_ORDERDETAILS_REQUEST = 'ADMIN_ORDERDETAILS_REQUEST'
export const ADMIN_ORDERDETAILS_SUCCESS = 'ADMIN_ORDERDETAILS_SUCCESS'
export const ADMIN_ORDERDETAILS_FAIL = 'ADMIN_ORDERDETAILS_FAIL'

export const DISPATCHEDORDER_REQUEST = 'DISPATCHEDORDER_REQUEST'
export const DISPATCHEDORDER_SUCCESS = 'DISPATCHEDORDER_SUCCESS'
export const DISPATCHEDORDER_FAIL = 'DISPATCHEDORDER_FAIL'

export const DELIVERORDER_REQUEST = 'DELIVERORDER_REQUEST'
export const DELIVERORDER_SUCCESS = 'DELIVERORDER_SUCCESS'
export const DELIVERORDER_FAIL = 'DELIVERORDER_FAIL'