export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'


export const USER_GETPRODUCTS_REQUEST = 'USER_GETPRODUCTS_REQUEST'
export const USER_GETPRODUCTS_SUCCESS = 'USER_GETPRODUCTS_SUCCEES'
export const USER_GETPRODUCTS_FAIL = 'USER_GETPRODUCTS_FAIL'


export const USER_GETCATEGORIES_REQUEST = 'USER_GETCATEGORIES_REQUEST'
export const USER_GETCATEGORIES_SUCCESS = 'USER_GETCATEGORIES_SUCCEES'
export const USER_GETCATEGORIES_FAIL = 'USER_GETCATEGORIES_FAIL'


export const USER_GETPRODUCT_REQUEST = 'USER_GETPRODUCT_REQUEST'
export const USER_GETPRODUCT_SUCCESS = 'USER_GETPRODUCT_SUCCEES'
export const USER_GETPRODUCT_FAIL = 'USER_GETPRODUCT_FAIL'

export const USER_GETCATEGORY_REQUEST = 'USER_GETCATEGORY_REQUEST'
export const USER_GETCATEGORY_SUCCESS = 'USER_GETCATEGORY_SUCCESS'
export const USER_GETCATEGORY_FAIL = 'USER_GETCATEGORY_FAIL'


export const USER_GETSUBCATEGORIES_REQUEST = 'USER_GETSUBCATEGORIES_REQUEST'
export const USER_GETSUBCATEGORIES_SUCCESS = 'USER_GETSUBCATEGORIES_SUCCESS'
export const USER_GETSUBCATEGORIES_FAIL = 'USER_GETSUBCATEGORIES_FAIL'

export const USER_GETPRODUCTLIST_REQUEST = 'USER_GETPRODUCTLIST_REQUEST'
export const USER_GETPRODUCTLIST_SUCCESS = 'USER_GETPRODUCTLIST_SUCCESS'
export const USER_GETPRODUCTLIST_FAIL = 'USER_GETPRODUCTLIST_FAIL'


export const USER_ADDTOCART_REQUEST = 'USER_ADDTOCART_REQUEST'
export const USER_ADDTOCART_SUCCESS = 'USER_ADDTOCART_SUCCESS'
export const USER_ADDTOCART_FAIL = 'USER_ADDTOCART_FAIL'




export const USER_GETCARTLIST_REQUEST = 'USER_GETCARTLIST_REQUEST'
export const USER_GETCARTLIST_SUCCESS = 'USER_GETCARTLIST_SUCCESS'
export const USER_GETCARTLIST_FAIL = 'USER_GETCARTLIST_FAIL'



export const USER_DELETECART_REQUEST = 'USER_DELETECART_REQUESTT'
export const USER_DELETECART_SUCCESS = 'USER_DELETECART_SUCCESS'
export const USER_DELETECART_FAIL = 'USER_DELETECART_FAIL'


export const USER_ORDER_REQUEST = 'USER_ORDER_REQUEST'
export const USER_ORDER_SUCCESS = 'USER_ORDER_SUCCESS'
export const USER_ORDER_FAIL = 'USER_ORDER_FAIL'

export const USER_GETORDER_REQUEST = 'USER_GETORDER_REQUEST'
export const USER_GETORDER_SUCCESS = 'USER_GETORDER_SUCCESS'
export const USER_GETORDER_FAIL = 'USER_GETORDER_FAIL'